insert into medicos (receita, compras_produtos_id, medicos_id) values ('Cyanea cylindrocalyx (Rock) Lammers', 816, 82);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Menegazzia terebrata (Hoffm.) A. Massal.', 876, 68);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Rinodina gennarii Bagl.', 216, 29);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lilium bulbiferum L.', 148, 24);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Sida tragiifolia A. Gray', 735, 8);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Dubautia reticulata (Sherff) D.D. Keck', 694, 64);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Maclura tinctoria (L.) D. Don ex Steud.', 741, 62);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Tetrazygia biflora (Cogn.) Urb.', 282, 88);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Enterosora Baker', 425, 45);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Rumex salicifolius Weinm. var. transitorius (Rech. f.) J.C. Hickman', 624, 32);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Hieracium praealtum Vill. ex Gochnat', 756, 68);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Fontinalis novae-angliae Sull. var. novae-angliae', 27, 55);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Palustriella Ochyra', 954, 38);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Halophila ovalis (R. Br.) Hook. f.', 942, 6);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Crataegus tristis Beadle', 972, 38);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Agalinis auriculata (Michx.) S.F. Blake', 763, 28);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Astragalus L.', 701, 66);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Thelypteris hildae Proctor', 245, 70);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Sinosenecio B. Nord.', 28, 41);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Manilkara valenzuela (A. Rich.) T.D. Penn.', 444, 51);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Acamptopappus sphaerocephalus (Harv. & A. Gray ex A. Gray) A. Gray var. hirtellus S.F. Blake', 757, 41);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Quercus ×willdenowiana (Dippel) Beissner, Schelle & Zabel (pro sp.)', 332, 33);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Hygrohypnum alpinum (Lindb.) Loeske', 160, 35);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Pseudognaphalium austrotexanum G.L. Nesom', 38, 98);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Zygodon reinwardtii (Hornsch.) A. Br.', 862, 89);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Cyrtandra ×georgiana Forbes (pro sp.)', 685, 38);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Castilleja montigena Heckard', 884, 58);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Gilia tenuiflora Benth. ssp. amplifaucalis A.D. Grant & V.E. Grant', 431, 57);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lomatium bicolor (S. Watson) J.M. Coult. & Rose var. bicolor', 61, 101);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Oxytropis kokrinensis A.E. Porsild', 793, 28);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Rorippa curvisiliqua (Hook.) Besser ex Britton var. occidentalis (Greene) R. Stuckey', 517, 88);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lepechinia Willd.', 861, 44);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lomariopsis Fée', 38, 47);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Palafoxia arida B.L. Turner & Morris var. gigantea (M.E. Jones) B.L. Turner & Morris', 460, 14);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Oreonana purpurascens Shevock & Constance', 518, 4);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Agave phillipsiana W.C. Hodgson', 737, 45);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Eriogonum aliquantum Reveal', 703, 3);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Pseudoleskea incurvata (Hedw.) Loeske', 168, 61);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Leptochloa divaricatissima S.T. Blake', 485, 52);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Claytonia perfoliata Donn ex Willd.', 468, 40);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Caloplaca rubrofusca (de Lesd.) ?, ined.?', 373, 73);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Dicranum spadiceum J.E. Zetterst.', 658, 31);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Mimosa microphylla Dryand.', 880, 16);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Mentzelia perennis Wooton', 218, 10);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Astragalus monoensis Barneby', 864, 88);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Pachycereus (A. Berger) Britton & Rose', 481, 92);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Cupaniopsis Radlk.', 566, 84);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Tortula cainii H.A. Crum & L.E. Anderson', 804, 15);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Quercus ×diversiloba Tharp ex A. Camus', 125, 80);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Ipomopsis aggregata (Pursh) V.E. Grant ssp. weberi V.E. Grant & Wilken', 223, 40);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Phlox pilosa L. ssp. fulgida (Wherry) Wherry', 435, 67);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Astragalus trichopodus (Nutt.) A. Gray var. phoxus (M.E. Jones) Barneby', 411, 58);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Echinodorus tenellus (Mart. ex Schult. f.) Buchenau', 22, 52);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Abronia argillosa S.L. Welsh & Goodrich', 232, 34);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Cladonia botrytes (K. Hagen) Willd.', 982, 4);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Xylorhiza glabriuscula Nutt. var. glabriuscula', 631, 73);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Spiraea chamaedryfolia L. var. ulmifolia (Scop.) Maxim.', 29, 86);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Stereophyllum Mitt.', 10, 15);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Erysimum arenicola S. Watson', 159, 30);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Salix myrsinites L.', 810, 77);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Normandina Nyl.', 728, 95);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Guettarda valenzuelana A. Rich.', 282, 23);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Asclepias sullivantii Engelm. ex A. Gray', 747, 57);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Penstemon cyananthus Hook.', 269, 18);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Rubus regionalis (L.H. Bailey) L.H. Bailey', 86, 15);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Crataegus lumaria Ashe', 320, 62);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Quercus cedrosensis C.H. Mull.', 608, 24);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Castilla elastica Sessé ssp. elastica', 971, 79);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Posidonia K.D. Koenig', 765, 34);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lichina confinis (O.F. Müll.) C. Agardh', 302, 33);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Liatris ×ridgwayi Standl.', 598, 74);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Passiflora alata Dryand.', 700, 89);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Trifolium eriocephalum Nutt. ssp. cusickii (Piper) J.M. Gillett', 51, 8);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Agalinis plukenetii (Elliott) Raf.', 777, 76);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Navarretia atractyloides (Benth.) Hook. & Arn.', 139, 60);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Viola lithion N.H. Holmgren & P.K. Holmgren', 440, 32);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Syringa ×chinensis Willd. [excluded]', 578, 32);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Gilia scopulorum M.E. Jones', 373, 13);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Carex longii Mack.', 654, 81);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Claytonia sibirica L. var. bulbifera A. Gray', 573, 43);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Parmentiera cereifera Seem.', 37, 93);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Opuntia ×occidentalis Engelm. & J.M. Bigelow (pro sp.)', 418, 100);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Caragana boisii C.K. Schneid.', 330, 73);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Eriogonum cithariforme S. Watson var. agninum (Greene) Reveal', 789, 81);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Bruchia vogesiaca Nestl. ex Schwägr.', 856, 62);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Heuchera alba Rydb.', 375, 64);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Castilleja pallescens (A. Gray) Greenm. var. pallescens', 31, 62);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lonchocarpus cyanescens (Schumach. & Thonn.) Benth.', 806, 65);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Eriochloa polystachya Kunth', 594, 95);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Skimmia Thunb.', 760, 87);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Aeonium Webb & Bethel.', 214, 61);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Lomatium scabrum (J.M. Coult. & Rose) Mathias var. tripinnatum Goodrich', 31, 70);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Polanisia erosa (Nutt.) Iltis', 301, 100);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Candelaria concolor (Dicks.) Stein var. effusa (Tuck.) G. Merr. & Burnham', 552, 66);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Melicope obovata (H. St. John) T.G. Hartley & B.C. Stone', 897, 24);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Gundlachia corymbosa (Urb.) Britton ex Boldingh', 290, 13);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Acalypha phleoides Cav.', 243, 61);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Monolopia major DC.', 133, 44);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Mammillaria dioica K. Brandegee', 437, 64);
insert into medicos (receita, compras_produtos_id, medicos_id) values ('Poncirus Raf.', 919, 26);
