insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Bryoria simplicior (Vain.) Brodo & D. Hawksw.', 495, 20);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Trillium albidum J.D. Freeman', 962, 16);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Scleria testacea Nees', 417, 1);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ramalina cochlearis Zahlbr.', 681, 8);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lomatium concinnum (Osterh.) Mathias', 128, 44);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pittosporum ×monae Rock ex H. St. John (pro sp.)', 545, 16);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dicerandra linearifolia (Elliott) Benth. var. robustior R.B. Huck', 162, 58);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lantana depressa Small', 757, 41);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Corchorus trilocularis L.', 838, 64);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Astragalus oophorus S. Watson var. oophorus', 343, 76);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Trifolium depauperatum Desv. var. depauperatum', 63, 61);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Drepanocladus pseudosarmentosus (Cardot & Thér.) Perss.', 385, 39);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pyrenopsis phaeococca Tuck.', 524, 12);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rubus persistens Rydb.', 766, 16);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dracontium polyphyllum L.', 199, 12);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Amblyolepis DC.', 999, 2);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Coccoloba sintenisii Urb. ex Lindau', 908, 44);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Salix matsudana Koidzumi', 245, 96);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lysimachia haupuensis H. St. John', 381, 65);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pinanga insignis Becc.', 27, 85);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Helianthemum scoparium Nutt.', 304, 23);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Bastardia bivalvis (Cav.) Kunth', 549, 74);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cyrtandra ×hosakae H. St. John & Storey (pro sp.)', 839, 79);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hamatocaulis lapponicus (Norrl.) Hedenäs', 1000, 89);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Galearis Raf.', 488, 46);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Salix glauca L. ssp. callicarpaea (Trautv.) Böcher', 227, 14);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Phlox speciosa Pursh ssp. occidentalis (Durand ex Torr.) Wherry', 441, 59);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Haematomma A. Massal.', 477, 72);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Macradenia lutescens R. Br.', 187, 18);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Wedelia parviflora Rich.', 966, 47);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Arenaria congesta Nutt. var. lithophila (Rydb.) Maguire', 288, 24);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cucumis melo L.', 67, 86);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Oxalis frutescens L.', 183, 41);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Evax prolifera Nutt. ex DC.', 514, 35);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Gentiana austromontana Pringle & Sharp', 28, 55);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Relicina (Hale & Kurok.) Hale', 969, 42);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hypogymnia bitteri (Lynge) Ahti', 272, 67);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Minuartia cumberlandensis (B.E. Wofford & Kral) McNeill', 24, 19);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dipsacus sativus (L.) Honck.', 203, 38);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Penstemon arenarius Greene', 857, 54);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Euonymus bungeanus Maxim.', 448, 99);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eriogonum umbellatum Torr. var. ellipticum (Nutt.) Reveal', 938, 48);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Clausena dentata (Willd.) M. Roem.', 601, 20);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Avicennia africana P. Beauv.', 911, 88);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Poranopsis paniculata (Roxb.) Roberty', 923, 83);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cayaponia Silva Manso', 256, 64);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Veronica peregrina L. ssp. xalapensis (Kunth) Pennell', 64, 67);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Amblystegium Schimp.', 504, 79);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Navarretia myersii Allen & Day ssp. deminuta Day', 313, 2);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Romulea Maratti', 879, 26);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Liparis Rich.', 493, 53);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Salix monochroma C.R. Ball', 51, 84);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Plagiomnium ciliare (Müll. Hal.) T. Kop.', 87, 88);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Penstemon pseudospectabilis M.E. Jones ssp. pseudospectabilis', 885, 62);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Parmotrema praesorediosum (Nyl.) Hale', 996, 101);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Descurainia incana (Bernh. ex Fisch. & C.A. Mey.) Dorn ssp. procera (Greene) Kartesz & Gandhi', 829, 49);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Acorus calamus L.', 454, 5);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cyperus fauriei Kük.', 942, 57);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hymenachne amplexicaulis (Rudge) Nees', 295, 62);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Adenophorus epigaeus (Bishop) W.H. Wagner', 828, 68);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eryngium foetidum L.', 336, 3);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Juncus drummondii E. Mey. var. drummondii', 945, 64);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Crepis bakeri Greene ssp. cusickii (Eastw.) Babc. & Stebbins', 581, 32);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eucalyptus microcorys F. Muell.', 957, 74);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Poa tenerrima Scribn.', 765, 81);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Stachytarpheta cayennensis (Rich.) Vahl', 932, 74);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dipsacus sativus (L.) Honck.', 783, 88);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Gunnera manicata Linden', 750, 100);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Claopodium crispifolium (Hook.) Renauld & Cardot', 137, 16);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cryptantha weberi I.M. Johnst.', 877, 18);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ribes californicum Hook. & Arn. var. californicum', 304, 82);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Graphis subnitidula Nyl.', 623, 59);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pectocarya peninsularis I.M. Johnst.', 826, 47);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eriogonum cernuum Nutt. var. cernuum', 34, 101);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rhododendron maximum L.', 702, 37);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Spiraea splendens Baumann ex K. Koch var. splendens', 976, 20);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Andropogon glomeratus (Walter) Britton, Sterns & Poggenb. var. hirsutior (Hack.) C. Mohr', 208, 19);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Macrothelypteris (H. Itô) Ching', 834, 40);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Clematis baldwinii Torr. & A. Gray', 661, 97);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Amorpha canescens Pursh', 622, 42);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Juniperus L.', 879, 46);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Caltha leptosepala DC. ssp. leptosepala var. sulfurea C.L. Hitchc.', 958, 30);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ipomopsis thurberi (Torr. ex A. Gray) V.E. Grant', 290, 36);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Alnus viridis (Chaix) DC. ssp. fruticosa (Rupr.) Nyman', 864, 61);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hedera helix L. ssp. canariensis (Willd.) Cout.', 654, 43);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Amsonia ciliata Walter', 251, 25);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Oligotrichum aligerum Mitt.', 953, 50);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Malachra fasciata Jacq.', 33, 50);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Arabis breweri S. Watson var. pecuniaria Rollins', 668, 61);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Astragalus wardii A. Gray', 143, 29);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Triglochin gaspensis Lieth & D. Löve', 168, 61);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Euphorbia rosescens E.L.Bridges & Orzell', 491, 88);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Parthenium tetraneuris Barneby', 890, 73);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lupinus pallidus Brandegee', 683, 28);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ipomoea tiliacea (Willd.) Choisy', 155, 98);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Sonchus arvensis L. ssp. arvensis', 5, 53);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pentaclethra Benth.', 393, 21);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hieracium argutum Nutt.', 530, 65);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lethariicola cucularis (Norman) Lumbsch & D. Hawksw.', 283, 67);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Copaifera officinalis (Jacq.) L.', 341, 6);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eucalyptus fruticetorum F. Muell.', 627, 7);
