insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Symphyotrichum campestre (Nutt.) G.L. Nesom', 104, 93);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Stenogyne calaminthoides A. Gray', 682, 85);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pycnanthemum montanum Michx.', 20, 95);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Tephrosia lindheimeri A. Gray', 606, 91);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ipomopsis macrosiphon (Kearney & Peebles) V.E. Grant & Wilken', 64, 9);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Mammillaria nivosa Link ex N.E. Pfeiffer', 717, 81);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Styphnolobium japonicum (L.) Schott', 71, 51);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Erodium cicutarium (L.) L''Hér. ex Aiton ssp. cicutarium', 250, 78);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lobelia monostachya (Rock) Lammers', 752, 75);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lechea maritima Leggett ex Britton, Sterns & Poggenb. var. maritima', 946, 6);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Draba petrophila Greene var. petrophila', 331, 38);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cotyledon orbiculata L.', 912, 84);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Githopsis pulchella Vatke ssp. campestris Morin', 229, 22);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Chrysopsis linearifolia Semple', 307, 79);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pleiacanthus Rydb.', 315, 71);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cordylanthus pilosus A. Gray ssp. trifidus (B.L. Rob. & Greenm.) T.I. Chuang & Heckard', 862, 97);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Streptopus ×oreopolus Fernald (pro sp.)', 505, 5);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Evolvulus filipes Mart.', 250, 96);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Brickellia veronicifolia (Kunth) A. Gray var. petrophila (B.L. Rob.) B.L. Rob.', 134, 53);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Sisymbrium L.', 580, 77);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Stellaria irrigua Bunge', 87, 17);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hypericum hookerianum Wight & Arn.', 478, 86);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Astragalus neglectus (Torr. & A. Gray) Sheldon', 386, 41);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Potamogeton natans L.', 542, 97);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Streptanthus morrisonii F.W. Hoffm. ssp. hirtiflorus F.W. Hoffm.', 799, 45);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Chorizanthe cuspidata S. Watson var. cuspidata', 655, 55);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pinus massoniana Lamb.', 538, 83);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cladonia glauca Flörke', 287, 44);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Angelica archangelica L. ssp. norvegica (Rupr.) Nordh.', 658, 95);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Astragalus acutirostris S. Watson', 639, 68);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lobaria oregana (Tuck.) Müll. Arg.', 472, 56);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Penstemon fremontii Torr. & A. Gray ex A. Gray var. glabrescens Dorn & Lichvar', 635, 90);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Phyllopsora glabella (Nyl.) Gotth. Schneid.', 32, 76);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Neogaerrhinum filipes (A. Gray) Rothm.', 732, 93);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Sphaeralcea coccinea (Nutt.) Rydb. ssp. elata (Baker f.) Kearney', 284, 19);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Helenium linifolium Rydb.', 952, 83);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eriogonum concinnum Reveal', 356, 46);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lipocarpha occidentalis (A. Gray) G. Tucker', 152, 6);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Triplophyllum funestum (Kunze) Holttum', 513, 87);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eriogonum racemosum Nutt.', 207, 79);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pleuraphis jamesii Torr.', 91, 19);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hedysarum L.', 556, 99);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Psilotum complanatum Sw.', 328, 29);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Clematis campaniflora Brot.', 949, 94);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Acacia retusa (Jacq.) Howard', 768, 39);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Pedicularis langsdorffii Fisch. ex Stev. ssp. arctica (R. Br.) Pennell', 762, 37);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Erythronium oregonum Applegate ssp. leucandrum (Applegate) Applegate', 924, 96);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Matelea alabamensis (Vail) Woodson', 875, 9);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Coreopsis basalis (A. Dietr.) S.F. Blake', 359, 4);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cheirodendron platyphyllum (Hook. & Arn.) Seem. ssp. platyphyllum', 495, 41);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Epilobium palustre L.', 665, 52);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Phlox pilosa L. ssp. deamii Levin', 221, 7);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rudbeckia nitida Nutt.', 152, 78);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dichanthelium commutatum (Schult.) Gould', 565, 9);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Garrya Douglas ex Lindl.', 691, 81);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Acacia neovernicosa Isely', 629, 31);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Penstemon clevelandii A. Gray', 240, 15);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Echinomastus gautii (L.D. Benson) Mosco & Zanovello', 419, 55);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Dudleya calcicola Bartel & Shevock', 157, 51);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rhizophora mangle L.', 530, 24);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hyparrhenia Andersson ex Fourn.', 856, 57);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Fragaria cascadensis K.E. Hummer', 803, 29);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Botrychium crenulatum W.H. Wagner', 146, 97);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Graphina substriatula (Nyl.) Zahlbr.', 483, 59);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lepanthes Sw.', 831, 15);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ludwigia curtissii Chapm.', 251, 82);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Hamamelis vernalis Sarg.', 63, 9);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cardiospermum L.', 870, 69);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Carex rossii Boott', 276, 89);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cirsium clavatum (M.E. Jones) Petr.', 650, 36);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Platanthera ×lassenii Schrenk', 69, 52);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Eriogonum sphaerocephalum Douglas ex Benth. var. sphaerocephalum', 896, 62);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Aquilegia coerulea James var. coerulea', 636, 14);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Cyperus plukenetii Fernald', 886, 85);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Phlox diffusa Benth.', 733, 23);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Harmonia hallii (D.D. Keck) B.G. Baldw.', 470, 40);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Sidalcea keckii Wiggins', 705, 57);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Aptenia cordifolia (L. f.) Schwant.', 268, 59);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Desmodium umbellatum (L.) DC.', 947, 86);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rhus copallinum L. var. latifolia Engl.', 731, 2);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Lyrocarpa coulteri Hook. & Harv. ex Harv. var. coulteri', 314, 69);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Amsonia longiflora Torr. var. longiflora', 478, 74);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Bryum flaccidum Brid.', 662, 5);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Horkelia fusca Lindl. ssp. fusca', 303, 60);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Sida glomerata Comm. ex Cav.', 443, 56);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Rumex albescens Hillebr.', 583, 25);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Afzelia africana Sm. ex Pers.', 221, 52);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Silene nivea (Nutt.) Muhl. ex Otth', 987, 62);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Prunus maritima Marshall var. maritima', 866, 1);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Viola blanda Willd. var. blanda', 349, 52);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Ipomopsis congesta (Hook.) V.E. Grant ssp. crebrifolia (Nutt.) Day', 880, 52);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Vernonia baldwinii Torr. ssp. baldwinii', 170, 100);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Vicia cracca L. ssp. cracca', 552, 64);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Robinia pseudoacacia L.', 132, 55);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Larix Mill.', 718, 69);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Draba sphaeroides Payson', 898, 79);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Oxytenia acerosa Nutt.', 259, 94);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Conioselinum mexicanum J.M. Coult. & Rose', 518, 81);
insert into receita_medica (receita, compras_produtos_id, medicos_id) values ('Gilia leptantha Parish ssp. transversa A.D. Grant & V.E. Grant', 824, 75);
